package analyzer.models.ranking;

public enum RankingType {
    MOST_MESSAGES,
    MOST_EMBEDS,
    MOST_ATTACHMENTS,
    TIMES_MENTIONED,
    ACCOUNT_AGE,
    MOST_COMMON_REACTION,
    AVG_WORD_COUNT,
    MENTION_NETWORK,
    MOST_MENTIONS_SENT,
    SOCIAL_GRAPH_MATRIX
}
